[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "bookt-domain"
version = "0.0.1"
dependencies = [
    "cosmos @ git+https://github.com/bgswe/cosmos",
    "bcrypt",
]

[tool.pytest.ini_options]
pythonpath = "src"
